
name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run onsed -i 's/\/argocd-app:.*/\/argocd-app:1.0/' argocd/dev/deployment.yaml
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: making a dynamic manifest file
        run: |
          git clone https://github.com/babumohan-1398-gmail-com/argocd.git
          sed -i 's/\/argocd-app:.*/\/argocd-app:1.1/' argocd/dev/deployment.yaml
          cd argocd/dev/
          git config --global user.email "babumohan.1398@gmail.com"
          git config --global user.name "babumohan1398"
          git add .
          git commit -m "pusjhing to new image"
          git push origin main
